name: Fuse Utils For macOS
run-name: Build Fuse Utils for macOS / ${{ github.actor }} /

# Executed upon each commit pushed, merge commit in PR
on: [push, pull_request]

jobs:
  libspectrum:
    # Build libspectrum locally (all libs enabled, real glib)
    name: "Libspectrum lib (macOS)"
    uses: ./.github/workflows/build_libspectrum_macos_sub.yml
    with:
      key: fuse-utils


#########################################
### SUPPORTED macOS configurations ###
#########################################

  # Default build without any configure params
  utils-default:
    name: "Fuse Utils Default (Utils)"
    needs: [libspectrum]
    uses: ./.github/workflows/build_macos_sub.yml
    with:
      name: Default
      dependencies: ""
      configure_params: ""
